name: Build Single HTML File

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build Single File
        run: VITE_SINGLEFILE=true npm run build
      - name: Rename missing artifact
        run: mv dist/index.html dist/PesachHaggadah.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: pesach-haggadah-singlefile
          path: dist/PesachHaggadah.html
